import express from 'express'
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.get("/api/spots", (req, res)=>{
    res.json({
  "spots": [
    {
      "spotId": 1,
      "name": "Цонжин Болдог",
      "area": "Төв",
      "category": "Соёл",
      "activities": [
        "Морин аялал",
        "Амьтантай ойр"
      ],
      "rating": 4.5,
      "price": 20000,
      "priceText": "20,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Төв аймгийн Эрдэнэ сумын нутагт байрладаг.",
      "openingHours": "09:00–18:00",
      "status": "Нээлттэй",
      "imgMainUrl": "https://lp-cms-production.imgix.net/2023-07/shutterstockRF1229637994.jpg",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Цонжин Болдог нь Монголын аялал жуулчлалын чухал цэгүүдийн нэг.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 2,
      "name": "Амарбаясгалант хийд",
      "area": "Сэлэнгэ",
      "category": "Түүхэн, Соёл",
      "activities": [
        "Уран барилга",
        "Түүхийн аялал"
      ],
      "rating": 4.3,
      "price": 500000,
      "priceText": "500,000₮",
      "ageRange": "18–45",
      "detailLocation": "Сэлэнгэ аймгийн Баруунбүрэн сумын нутаг.",
      "openingHours": "09:00–18:00",
      "status": "Нээлттэй",
      "imgMainUrl": "https://lp-cms-production.imgix.net/2023-07/shutterstockRF567790018.jpg",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "Долоо хоногийн бүх өдөр: 08–18 цаг",
      "descriptionLong": "Амарбаясгалант хийд нь Монголын шашин, соёлын үнэт өв юм.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 3,
      "name": "Хустайн байгалийн цогцолборт газар",
      "area": "Төв",
      "category": "Байгаль",
      "activities": [
        "Зэрлэг адуу харах",
        "Аялал"
      ],
      "rating": 4.7,
      "price": 15000,
      "priceText": "15,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Төв аймгийн Аргалант сумын нутаг.",
      "openingHours": "08:00–20:00",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1586769852836-e9b73c556b36",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Хустайн байгалийн цогцолборт газар нь тахийг сэргээн нутагшуулснаараа алдартай.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 4,
      "name": "Горхи-Тэрэлж Үндэсний Парк",
      "area": "Төв",
      "category": "Байгаль",
      "activities": [
        "Агаарт гарах",
        "Морин аялал"
      ],
      "rating": 4.8,
      "price": 10000,
      "priceText": "10,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Налайх дүүргээс хойд зүгт байрладаг.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Горхи-Тэрэлж нь Улаанбаатар хотын ойролцоох аялал жуулчлалын бүс.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 5,
      "name": "Шар Нохой хад",
      "area": "Төв",
      "category": "Байгаль",
      "activities": [
        "Гэрэл зураг авах",
        "Хадан аялал"
      ],
      "rating": 4.2,
      "price": 5000,
      "priceText": "5,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Горхи-Тэрэлжийн бүсэд байрладаг.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1542744095-291d1f67b221",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Шар Нохой хад нь өвөрмөц хэлбэр бүхий байгалийн тогтоцтой хад юм.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 6,
      "name": "Улаанбаатар Хүрээ музей",
      "area": "Улаанбаатар",
      "category": "Түүхэн",
      "activities": [
        "Музейн үзмэр",
        "Түүхийн аялал"
      ],
      "rating": 4.0,
      "price": 0,
      "priceText": "Үнэгүй",
      "ageRange": "Бүх нас",
      "detailLocation": "Улаанбаатар хотын төв хэсэгт байрладаг.",
      "openingHours": "10:00–18:00",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1583508915901-b5f84c1dcde1",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Улаанбаатар Хүрээ музей нь нийслэлийн түүхийг харуулсан сонирхолтой музей юм.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 7,
      "name": "Гандан Тэгчинлэн Хийд",
      "area": "Улаанбаатар",
      "category": "Соёл, Шашин",
      "activities": [
        "Шашны зан үйл",
        "Сүм үзэх"
      ],
      "rating": 4.9,
      "price": 5000,
      "priceText": "5,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Баянгол дүүрэг, 16-р хороо.",
      "openingHours": "07:00–20:00",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1524492514791-505e3bfb9c51",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Гандан Тэгчэнлин хийд нь Монголын хамгийн том буддын хийдүүдийн нэг.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 8,
      "name": "Богд хан уул",
      "area": "Улаанбаатар",
      "category": "Байгаль ба түүх",
      "activities": [
        "Ууланд алхах",
        "Пикник"
      ],
      "rating": 4.8,
      "price": 0,
      "priceText": "Үнэгүй",
      "ageRange": "Бүх нас",
      "detailLocation": "Улаанбаатар хотын баруун-өмнөд хэсэгт байрладаг.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1519817650390-64a93db511aa",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Богд хан уул нь дэлхийн хамгийн эрт дархлагдсан уулуудын нэг.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 9,
      "name": "Хөвсгөл нуур",
      "area": "Хөвсгөл",
      "category": "Байгалийн үзэсгэлэнт",
      "activities": [
        "Зугаалга",
        "Усан аялал",
        "Зураг авалт"
      ],
      "rating": 5.0,
      "price": 30000,
      "priceText": "30,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Хөвсгөл аймгийн Хатгал тосгоны орчим.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Хөвсгөл нуур нь Монголын \"далай\" хэмээн алдаршсан гайхамшигт нуур.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 10,
      "name": "Орхон хүрхрээ",
      "area": "Өвөрхангай",
      "category": "Байгаль",
      "activities": [
        "Хүрхрээ үзэх",
        "Аялах"
      ],
      "rating": 4.7,
      "price": 15000,
      "priceText": "15,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Өвөрхангай аймгийн Бат-Өлзий сумын нутаг.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Орхон хүрхрээ нь Орхон голын доод хэсэгт орших байгалийн сонин тогтоцтой хүрхрээ.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 11,
      "name": "Эрдэнэзуу хийд",
      "area": "Өвөрхангай",
      "category": "Түүхэн, Соёл",
      "activities": [
        "Сүм хийд үзэх",
        "Түүхийн аялал"
      ],
      "rating": 4.6,
      "price": 10000,
      "priceText": "10,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Өвөрхангай аймгийн Хар хорин суманд байрладаг.",
      "openingHours": "09:00–18:00",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1524492514791-505e3bfb9c51",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Эрдэнэзуу хийд нь Монголын буддын шашны анхны томоохон хийдүүдийн нэг.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 12,
      "name": "Хорго галт уул",
      "area": "Архангай",
      "category": "Байгаль",
      "activities": [
        "Галт уулын тогоо үзэх",
        "Алхалт"
      ],
      "rating": 4.4,
      "price": 10000,
      "priceText": "10,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Архангай аймгийн Тариат сумын нутаг.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1519681393784-d120267933ba",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Хорго галт уул нь сүүлийн мөстлөгийн үеийн идэвхтэй байсан галт уулын үлдэц.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 13,
      "name": "Тэрхийн цагаан нуур",
      "area": "Архангай",
      "category": "Байгалийн үзэсгэлэнт",
      "activities": [
        "Зугаалга",
        "Зургийн аялал"
      ],
      "rating": 4.5,
      "price": 12000,
      "priceText": "12,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Архангай аймгийн Тариат сумын орчим.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Тэрхийн цагаан нуур нь галт уулын тогоонд үүссэн цэнгэг уст нуур юм.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 14,
      "name": "Алтай Таван богд",
      "area": "Баян-Өлгий",
      "category": "Адал явдалт, Байгаль",
      "activities": [
        "Ууланд авирах",
        "Трэкинг",
        "Мөсөрхүү аялал"
      ],
      "rating": 4.9,
      "price": 80000,
      "priceText": "80,000₮",
      "ageRange": "18–55",
      "detailLocation": "Баян-Өлгий аймгийн нутагт, Монгол Алтайн нуруунд байрладаг.",
      "openingHours": "06:00–20:00",
      "status": "Улирлын",
      "imgMainUrl": "https://images.unsplash.com/photo-1477414348463-c0eb7f1359b6",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Алтай Таван богд нь адал явдалт болон өндөр уулын аялалд тохиромжтой бүс.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 15,
      "name": "Говь гурван сайхан",
      "area": "Өмнөговь",
      "category": "Байгалийн цогцолбор",
      "activities": [
        "Цөлд аялах",
        "Хадны зураг үзэх"
      ],
      "rating": 4.8,
      "price": 60000,
      "priceText": "60,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Өмнөговь аймгийн нутаг, дунд болон баруун хэсэг.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1508261306211-45a1c5c2a5c5",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Говь гурван сайхан нь Говийн бүсийн онцлог тогтоцтой уулс юм.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 16,
      "name": "Хонгорын элс",
      "area": "Өмнөговь",
      "category": "Цөл, Байгаль",
      "activities": [
        "Элсэн довцог дээр алхах",
        "Тэмээ унах"
      ],
      "rating": 4.9,
      "price": 40000,
      "priceText": "40,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Өмнөговь аймгийн Сэврэй, Номгон сумдын зааг.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1542367592-8849eb950fd8",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Хонгорын элс нь дуут элсээрээ алдартай том элсэн манхан.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 17,
      "name": "Ёлын ам",
      "area": "Өмнөговь",
      "category": "Хавцал, Байгаль",
      "activities": [
        "Хавцалд алхах",
        "Мөсөн гол үзэх"
      ],
      "rating": 4.6,
      "price": 20000,
      "priceText": "20,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Говь гурван сайханы байгалийн цогцолборт газарт байрладаг.",
      "openingHours": "08:00–19:00",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1500534314211-0a24cd03f2c0",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Ёлын ам нь гүн хавцал, заримдаа жилийн турш мөстэй байдаг онцлогтой.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 18,
      "name": "Бурхан Халдун уул",
      "area": "Хэнтий",
      "category": "Түүхэн, Байгаль",
      "activities": [
        "Ууланд авирах",
        "Түүхийн аялал"
      ],
      "rating": 4.7,
      "price": 50000,
      "priceText": "50,000₮",
      "ageRange": "18–55",
      "detailLocation": "Хэнтий аймгийн Батширээт, Өмнөдэлгэр сумдын зааг.",
      "openingHours": "06:00–18:00",
      "status": "Улирлын",
      "imgMainUrl": "https://images.unsplash.com/photo-1519817650390-64a93db511aa",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Бурхан Халдун уул нь Чингис хааны домогтой холбогддог ариун хайрхан.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 19,
      "name": "Тайхар чулуу",
      "area": "Архангай",
      "category": "Домогт газар",
      "activities": [
        "Домог сонсох",
        "Зураг авах"
      ],
      "rating": 4.3,
      "price": 5000,
      "priceText": "5,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Архангай аймгийн Ихтамир сумын нутаг.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1526498460520-4c246339dccb",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Тайхар чулуу нь эртний бичээс, домог түүхтэй нүсэр хад юм.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 20,
      "name": "Хэрмэн цав",
      "area": "Дундговь",
      "category": "Геологийн сонин тогтоц",
      "activities": [
        "Цав үзэх",
        "Зураг авалт"
      ],
      "rating": 4.4,
      "price": 25000,
      "priceText": "25,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Дундговь аймгийн Говь-Угтаал орчим.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Хэрмэн цав нь газрын хөрс эвдрэлээс үүссэн гайхалтай геологийн тогтоцтой бүс.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 21,
      "name": "Сүхбаатарын талбай",
      "area": "Улаанбаатар",
      "category": "Хотын соёл",
      "activities": [
        "Хотын аялал",
        "Үйл ажиллагаа үзэх"
      ],
      "rating": 4.5,
      "price": 0,
      "priceText": "Үнэгүй",
      "ageRange": "Бүх нас",
      "detailLocation": "Улаанбаатар хотын төв талбай.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1534143046043-9e9a97e9b1c5",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Сүхбаатарын талбай нь нийслэл хотын төв цэг, олон нийтийн арга хэмжээний гол талбар.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 22,
      "name": "Зайсан толгой",
      "area": "Улаанбаатар",
      "category": "Хотын үзэмж",
      "activities": [
        "Хотыг дээрээс харах",
        "Кафе, ресторан"
      ],
      "rating": 4.6,
      "price": 0,
      "priceText": "Үнэгүй",
      "ageRange": "Бүх нас",
      "detailLocation": "Улаанбаатар хотын Хан-Уул дүүрэг.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Зайсан толгойгоос Улаанбаатар хотыг бүхэлд нь харж болно.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 23,
      "name": "Цагаан суварга",
      "area": "Дундговь",
      "category": "Цөл, Геологийн тогтоц",
      "activities": [
        "Цөлд алхах",
        "Зураг авалт"
      ],
      "rating": 4.7,
      "price": 30000,
      "priceText": "30,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Дундговь аймгийн Өлзийт сумын нутаг.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1542367592-8849eb950fd8",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Цагаан суварга нь салхины элэгдлээр үүссэн цагаан өнгийн хадан хананууд юм.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 24,
      "name": "Дадал - Чингис хааны төрсөн нутаг",
      "area": "Хэнтий",
      "category": "Түүхэн газар",
      "activities": [
        "Түүхийн аялал",
        "Байгальтай хосолсон аялал"
      ],
      "rating": 4.6,
      "price": 40000,
      "priceText": "40,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Хэнтий аймгийн Дадал сум.",
      "openingHours": "08:00–20:00",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Дадал сум нь Чингис хааны төрсөн нутаг хэмээн алдаршсан түүхэн бүс.",
      "infoPageHref": "../code/index.html#/spot-info"
    },
    {
      "spotId": 25,
      "name": "Увс нуур",
      "area": "Увс",
      "category": "Байгалийн цогцолбор",
      "activities": [
        "Шувуу ажиглах",
        "Нуурын аялал"
      ],
      "rating": 4.8,
      "price": 35000,
      "priceText": "35,000₮",
      "ageRange": "Бүх нас",
      "detailLocation": "Увс аймгийн баруун хэсэгт.",
      "openingHours": "24/7",
      "status": "Нээлттэй",
      "imgMainUrl": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
      "img2Url": null,
      "img3Url": null,
      "mapSrc": "../files/Mongolia_blank.svg",
      "scheduleFull": "",
      "descriptionLong": "Увс нуур, түүний орчмын экосистем нь ЮНЕСКО-ийн дэлхийн өвд бүртгэгдсэн.",
      "infoPageHref": "../code/index.html#/spot-info"
    }
  ]
}
)
})

//app.post("/api/posts", )
app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
